Demander signatures service
uclouvain/osis-admission pull request #26
Opened 2021-11-18 11:00 UTC by AL9000

2021-11-18 13:15 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/_should_detail_projet_etre_complete.py
> +    proposition = attr.ib(type="Proposition")  # type: Proposition
Tu pourrais recevoir directement le projet

2021-11-18 13:15 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/_should_detail_projet_etre_complete.py
> +        project = proposition.projet
Rester en français :)

2021-11-18 13:15 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/exceptions.py
> +        message = _("Mandatory fields are missing in the projet details of the proposition.")
```suggestion
        message = _("Mandatory fields are missing in the project details of the proposition.")
```

2021-11-18 13:15 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/validator_by_business_action.py
> +    proposition = attr.ib(type='Proposition')  # type: Proposition
Idem ne recevoir que ce dont tu as besoin, donc le projet

2021-11-18 13:15 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/_should_detail_projet_etre_complete.py
> +        if project is None or not all(
Le projet ne peux pas être nul il me semble (c'est forcément un ValueObject de type DetailProjet)

2021-11-18 13:15 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/test/factory/proposition.py
> +    projet = None
En fait comme dit au dessus, un projet ne peut pas être nul (dans le DDD), mais il peut être vide. Du coup je te propose de reprendre le meme principe que `financement_non_rempli` et `aucune_experience_precedente_recherche` : instancie un `DetailProjet()` vide que tu nomme `projet_non_complete` dans `_detail_projet.py` puis tu n'as qu'à le référencer ici

2021-11-18 13:15 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/use_case/write/demander_signatures_service.py
> +    proposition_candidat.verifier_projet_doctoral()
Tu peux maintenant vérifier la cotutelle également

2021-11-18 13:15 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/model/proposition.py
> +    def verouiller_projet_doctoral_pour_signature(self):
En fait tu verrouille la proposition plutôt que le projet doctoral (car tu verrouille également la cotutelle et le groupe de supervision)

2021-11-18 13:40 UTC, AL9000 commented on ddd/preparation/projet_doctoral/domain/validator/_should_detail_projet_etre_complete.py
> +    proposition = attr.ib(type="Proposition")  # type: Proposition
Je ne pense pas car j'ai besoin de savoir le type de la proposition.

2021-11-18 13:42 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/_should_detail_projet_etre_complete.py
> +    proposition = attr.ib(type="Proposition")  # type: Proposition
Alors prends-la en paramètre également (cf `ShouldJustificationDonneeSiPreadmission`)

2021-11-18 13:44 UTC, AL9000 commented on ddd/preparation/projet_doctoral/domain/validator/validator_by_business_action.py
> +    proposition = attr.ib(type='Proposition')  # type: Proposition
J'en ai besoin dans le validator

2021-11-18 16:27 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/test/factory/groupe_de_supervision.py
> +    cotutelle = factory.SubFactory(_CotutelleFactory, motivation="Runs in family", institution="MIT")
Je te conseille de créer une autre factory, tu risque de faire péter des tests d'autres fichiers

2021-11-18 16:27 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/test/use_case/write/test_demander_signatures_service.py
> +        PropositionIdentityBuilder.build_from_uuid(self.uuid_proposition_sans_cotutelle)
Code mort ?

2021-11-18 16:27 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/test/use_case/write/test_demander_signatures_service.py
> +        uuid_proposition_admission = 'uuid-ECGE3DP'
Utile ?

2021-11-19 18:16 UTC, SebCorbin approved these changes

2021-11-23 10:46 UTC, SebCorbin requested changes

2021-11-23 10:46 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/_should_groupe_de_supervision_avoir_au_moins_un_membre_CA.py
> +    signatures_membres_CA = attr.ib(type=List[SignatureMembreCA], factory=list)  # type: List[SignatureMembreCA]
```suggestion
    signatures_membres_CA = attr.ib(type=List[SignatureMembreCA])  # type: List[SignatureMembreCA]
```

2021-11-23 10:46 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/_should_groupe_de_supervision_avoir_au_moins_un_promoteur.py
> +    signatures_promoteurs = attr.ib(type=List[SignaturePromoteur], factory=list)  # type: List[SignaturePromoteur]
```suggestion
    signatures_promoteurs = attr.ib(type=List[SignaturePromoteur])  # type: List[SignaturePromoteur]
```

2021-11-23 10:46 UTC, SebCorbin commented on infrastructure/preparation/projet_doctoral/domain/service/promoteur.py
> +        return False
```suggestion
        return Person.objects.get(global_id=identity.matricule).source == person_source_type.DOCTORAT
```

2021-11-23 10:46 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/_should_pre_admission_avoir_au_moins_un_promoteur_externe.py
> +            raise CotutelleDoitAvoirAuMoinsUnPromoteurExterneException
Tu es sur que ce fichier est toujours d'actualité ? En tout cas il fait pas la bonne vérif et il est mal nommé

2021-11-23 10:46 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/exceptions.py
> +        message = _("You must add at least one promoteur in order to request signatures.")
```suggestion
        message = _("You must add at least one promoter in order to request signatures.")
```

2021-11-23 10:46 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/exceptions.py
> +        message = _("You must add at least one external promoteur in order to request signatures.")
```suggestion
        message = _("You must add at least one external promoter in order to request signatures.")
```

2021-11-23 10:46 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/validator_by_business_action.py
> +            ShouldCotutelleAvoirAuMoinsUnPromoteurExterne(self.groupe_de_supervision),
A supprimer ?

2021-11-23 10:46 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/model/proposition.py
> +        DetailsProjetValidatorList(proposition=self).validate()
Ne passer que le projet et le type d'admission en paramètre

2021-11-23 10:46 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/use_case/write/demander_signatures_service.py
> +    proposition_candidat.verouiller_proposition_pour_signature()
Attention tu as oublié de faire un save là-dessus (rajoute dans tes tests que l'état de la proposition a changé)

2021-11-23 10:47 UTC, SebCorbin commented on ddd/preparation/projet_doctoral/domain/validator/validator_by_business_action.py
> +    proposition = attr.ib(type='Proposition')  # type: Proposition
et le type d'admission

2021-11-23 14:20 UTC, SebCorbin approved these changes

2021-11-24 07:43 UTC, BenJneB commented on ddd/preparation/projet_doctoral/test/use_case/write/test_demander_signatures_service.py
> +        self.uuid_proposition_sans_membre_CA = 'uuid-SC3DP-sans-membre_CA'
pourquoi mettre tout ceci dans le setup ?

2021-11-24 07:51 UTC, BenJneB commented on ddd/preparation/projet_doctoral/domain/model/_detail_projet.py
> +projet_incomplet = DetailProjet()
incomplet (pour moi) sous entend qu'il est partiellement rempli ?
projet_vide ? projet_non_rempli ?

2021-11-24 07:51 UTC, AL9000 commented on ddd/preparation/projet_doctoral/test/use_case/write/test_demander_signatures_service.py
> +        self.uuid_proposition_sans_membre_CA = 'uuid-SC3DP-sans-membre_CA'
C'est vrai que je peux juste référencer 'uuid des différentes propositions directement dans les tests. On en perdrait pas tellement en clarté.

2021-11-24 07:53 UTC, BenJneB commented on ddd/preparation/projet_doctoral/domain/model/_enums.py
> +    SIGNING_IN_PROGRESS = _('SIGNING_IN_PROGRESS')
J'ai un peu de mal avec cette enum ?
Elle représente le statut des signatures? Ou des signataires? 
Quelle est la différence entre SUBMITTED & SIGNING_IN_PROGRESS?

2021-11-24 07:54 UTC, AL9000 commented on ddd/preparation/projet_doctoral/domain/model/_detail_projet.py
> +projet_incomplet = DetailProjet()
En effet c'est beaucoup mieux de dire `projet_non_rempli` je pense.

2021-11-24 08:39 UTC, AL9000 commented on ddd/preparation/projet_doctoral/test/use_case/write/test_demander_signatures_service.py
> +        self.uuid_proposition_sans_membre_CA = 'uuid-SC3DP-sans-membre_CA'
@SebCorbin tu en penses quoi ?

2021-11-24 09:06 UTC, AL9000 commented on ddd/preparation/projet_doctoral/domain/model/_enums.py
> +    SIGNING_IN_PROGRESS = _('SIGNING_IN_PROGRESS')
J'ai eu aussi un peu de mal avec cette enum donc c'est très bien qu'on en discute ! :)
C'est sensé représenter le statut des sigantures en effet, et permettre de savoir à l'avenir si l'onglet de cotutelle sera verrouillé ou non.
Et en effet il n'y a pas de différences entre `SUBMITTED` et `SIGNING_IN_PROGRESS`...
Je ne sais pas si c'est une bonne chose alors d'avoir ce statut sur le groupe de supervision, @SebCorbin ?

2021-12-14 08:35 UTC, AL9000 commented on ddd/preparation/projet_doctoral/domain/validator/_should_cotutelle_etre_completee.py
> +        ):
c'est mieux aussi je trouve, en plus de diminuer le niveau ça simplifie la lecture. Surtout en DDD :)

2021-12-14 08:45 UTC, AL9000 commented on infrastructure/preparation/projet_doctoral/domain/service/promoteur.py
> +        return Person.objects.get(global_id=identity.matricule).source == person_source_type.DOCTORAT
`raise NotImplementedError` en attendant alors ?

2021-12-14 08:48 UTC, BenJneB commented on infrastructure/preparation/projet_doctoral/domain/service/promoteur.py
> +        return Person.objects.get(global_id=identity.matricule).source == person_source_type.DOCTORAT
Yep

2021-12-14 08:49 UTC, BenJneB approved these changes

2021-12-14 09:08 UTC, BenJneB approved these changes

2021-12-14 09:08 UTC, merged