WIP: Serializer field returning action links based on the user permissions
uclouvain/osis-admission pull request #33
Opened 2021-11-25 16:40 UTC by jcougnaud

2021-11-25 16:40 UTC, sips-uclouvain commented
Can one of the admins verify this patch?

2021-11-25 16:40 UTC, sips-uclouvain commented
Can one of the admins verify this patch?

2021-11-29 16:31 UTC, SebCorbin commented on api/schema.py
> +                        },
Il me semble que c'est un `OneOf(error, url)`, non ?

2021-11-29 16:31 UTC, SebCorbin commented on api/serializers/fields.py
> +                'The \'request\' property must be added to the serializer context to compute the action links.'
`Alt + Entrée`, "Convert single-quoted string with double-quoted string" ;)

2021-11-29 16:31 UTC, SebCorbin commented on api/serializers/fields.py
> +                    'Please check the following path exists: \'{}\''.format(action.get('path_name'))
Idem, reste sur des double quote pour éviter les echappement superflus

2021-11-29 16:31 UTC, SebCorbin commented on api/serializers/fields.py
> +                        'errors': e.args
Je pense que ça peut être pas mal de renvoyer la méthode demandée avec l'erreur

2021-11-29 16:31 UTC, SebCorbin commented on tests/api/serializers/test_fields.py
> +        return Response()
```suggestion
    def get(self, request, *args, **kwargs):
        return Response()
    
    delete  = get
    post = get
    put = get
```

2021-11-29 16:31 UTC, SebCorbin commented on tests/api/serializers/test_fields.py
> +        return Response()
Et ramène cette logique dans une mixin pour la factoriser sur tes classes ci-dessous (pour éviter d'avoir des doublons)

2021-11-30 11:41 UTC, jcougnaud commented on api/schema.py
> +                        },
Oui complètement, j'ai également modifié le schéma pour indiquer que la méthode est toujours renvoyée (cf https://github.com/uclouvain/osis-admission/pull/33#discussion_r758528698).

J'en ai aussi profité pour décaler la description d'un lien dans un composant, pour ainsi éviter de répéter cette description à chaque lien.

J'obtiens quelque chose comme ça :

```python
schema['components']['schemas']['ActionLink'] = {
    'type': 'object',
    'properties': {
        'errors': {
            'type': 'array',
            'items': {
                'type': 'string',
            },
        },
        'method': {
            'type': 'string',
            'enum': [
                'DELETE',
                'GET',
                'PATCH',
                'POST',
                'PUT',
            ],
        },
        'url': {
            'type': 'string',
            'format': 'uri',
        },
    },
    'oneOf': [
        {
            'required': ['method', 'url'],
        },
        {
            'required': ['method', 'errors'],
        }
    ],
}
```

2021-11-30 11:41 UTC, jcougnaud commented on api/serializers/fields.py
> +                'The \'request\' property must be added to the serializer context to compute the action links.'
D'accord ça marche, merci pour le raccourci. :+1:

2021-11-30 11:41 UTC, jcougnaud commented on api/serializers/fields.py
> +                    'Please check the following path exists: \'{}\''.format(action.get('path_name'))
Ok je vais essayer de prendre l'habitude de le faire partout.

2021-11-30 11:41 UTC, jcougnaud commented on api/serializers/fields.py
> +                        'errors': e.args
Ça marche, j'ai également modifié le schéma pour prendre en compte cette modification

2021-11-30 11:42 UTC, jcougnaud commented on tests/api/serializers/test_fields.py
> +        return Response()
Ok, en fait, après la modification de mes tests, je peux me passer de ces implémentations finalement.

Mais je garde l'idée en tête pour plus tard, merci.

2021-12-06 10:25 UTC, SebCorbin requested changes

2021-12-06 12:40 UTC, jcougnaud commented on api/schema.py
> +        }
Ça marche, je vais faire ça.

2021-12-07 12:47 UTC, albrugnetti commented on api/schema.py
> +            ],
Pourquoi avoir oneOf ? Obliger au minimum 'method' & 'url' n'est-il pas suffisant?

2021-12-07 12:47 UTC, albrugnetti commented on schema.yml
> +        - error
Adapter en fonction des remarques

2021-12-09 10:10 UTC, SebCorbin approved these changes

2021-12-09 14:40 UTC, BenJneB approved these changes

2022-01-04 08:42 UTC, albrugnetti commented on api/schema.py
> +            ],
@jcougnaud  Je me pose la question de l'intérêt du champ 'method' en cas d'action non autorisée ? Pourrais-tu m'éclaircir?

2022-01-04 09:33 UTC, SebCorbin commented on api/schema.py
> +            ],
En effet, l'action est déjà la clé du dictionnaire, donc le front se basera sur celle-ci pour déterminer si une action/un bouton est affichable. Docn on peut se passer de la méthode en cas d'erreur

2022-01-04 10:46 UTC, BenJneB approved these changes

2022-01-04 10:59 UTC, albrugnetti approved these changes

2022-01-04 11:00 UTC, merged