Api
uclouvain/osis-admission pull request #5
Opened 2021-04-01 13:47 UTC by AL9000

2021-04-06 10:18 UTC, SebCorbin requested changes

2021-04-06 10:18 UTC, SebCorbin commented on contrib/serializers/doctorate.py
> +    )
Je propose de séparer les serializers d'ecriture de ceux de lecture pour éviter d'avoir trop de champs à terme, ça permettra de rester sur des methodes `create` et `update` simples, d'autant qu'on risque d'avoir une foultitude de champs non primitifs

2021-04-06 14:28 UTC, AL9000 commented on contrib/serializers/doctorate.py
> +    )
C'est beaucoup plus lisible en effet !

2021-04-06 16:04 UTC, SebCorbin requested changes

2021-04-06 16:04 UTC, SebCorbin commented on contrib/serializers/doctorate.py
> +    author = serializers.StringRelatedField(read_only=True)
Les StringRelatedField sont read only par défaut

```suggestion
    url = serializers.ReadOnlyField(source="get_absolute_url")
    type = serializers.ReadOnlyField(source="get_type_display")
    candidate = serializers.StringRelatedField()
    author = serializers.StringRelatedField()
```

2021-04-06 16:04 UTC, SebCorbin commented on contrib/serializers/doctorate.py
> +
Je suis pas sûr que tu aies besoin de tout ça maintenant que tu as un serializer simple, le ModelSerializer devrait se charger de tout ça

2021-04-07 08:30 UTC, AL9000 commented on contrib/serializers/doctorate.py
> +
Alors je voulais que l'auteur de la demande soit renseigné automatiquement. Après je peux laisser le choix, tu préfères quoi ?

2021-04-07 09:39 UTC, SebCorbin approved these changes

2021-04-08 08:00 UTC, merged