[OS-550] Some fixes and updates in the faculty decision and comments tabs
uclouvain/osis-admission pull request #529
Opened 2023-10-30 13:53 UTC by jcougnaud

2023-10-30 15:00 UTC, jcougnaud commented
rerun unit tests

2023-11-02 08:36 UTC, albrugnetti requested changes

2023-11-02 08:36 UTC, albrugnetti commented on ddd/admission/formation_generale/domain/validator/_should_informations_checklist_etre_completees.py
> +            or self.checklist_actuelle.decision_facultaire.extra.get('decision') == '1'
Est-il possible de rendre plus explicite la valeur "1" dans le contexte de la decision_facultaire ?
**Suggestion:** Utilisation d'une enum "DecisionFacultaireEnum" avec les différentes valeurs possibles

2023-11-02 08:36 UTC, albrugnetti commented on ddd/admission/formation_generale/test/use_case/write/test_envoyer_proposition_au_sic_lors_de_la_decision_facultaire_service.py
> +        self.proposition.checklist_actuelle.decision_facultaire.extra = {'decision': '0'}
Utilisation de l'enum (cf. commentaire https://github.com/uclouvain/osis-admission/pull/529/files#diff-462d775088e4d11fc460611aa9380f104bf379666d49767fa3b464451c010949R109)

2023-11-02 08:36 UTC, albrugnetti commented on ddd/admission/formation_generale/test/use_case/write/test_envoyer_proposition_au_sic_lors_de_la_decision_facultaire_service.py
> +        self.proposition.checklist_actuelle.decision_facultaire.extra = {'decision': '1'}
Utilisation de l'enum (cf. commentaire https://github.com/uclouvain/osis-admission/pull/529/files#diff-462d775088e4d11fc460611aa9380f104bf379666d49767fa3b464451c010949R109)

2023-11-02 08:36 UTC, albrugnetti commented on views/common/detail_tabs/checklist.py
> +            )
Est-ce qu'il n'y a  pas un soucis dans le conditionnement (IF / ELSE / ...) ?

2023-11-02 11:08 UTC, jcougnaud commented on ddd/admission/formation_generale/domain/validator/_should_informations_checklist_etre_completees.py
> +            or self.checklist_actuelle.decision_facultaire.extra.get('decision') == '1'
Oui ça marche, j'ai ajouté cette énumération avec les valeurs (`EN_DECISION` et `HORS_DECISION`).

2023-11-02 11:10 UTC, jcougnaud commented on views/common/detail_tabs/checklist.py
> +            )
J'ai l'impression que cela fonctionne même si cela n'est peut être pas très clair comme on enchaîne deux `if-else` à la suite.

2023-11-02 14:20 UTC, albrugnetti approved these changes

2023-11-02 14:28 UTC, merged